function y = ForceFilterV2(x)
%FORCEFILTERV2 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 01-Aug-2016 21:32:18

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 20;    % Passband Frequency
    % Fstop = 35;    % Stopband Frequency
    % Apass = 1;     % Passband Ripple (dB)
    % Astop = 80;    % Stopband Attenuation (dB)
    % Fs    = 1000;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.96077429608528 0.977578573423497; 1 2 1 1 ...
        -1.91841418623923 0.934855427895394; 1 2 1 1 -1.87966659991762 ...
        0.895775766031979; 1 2 1 1 -1.84531728014321 0.861132064850686; 1 2 1 1 ...
        -1.81596325192971 0.831526466004056; 1 2 1 1 -1.7920433877587 ...
        0.807401603209682; 1 2 1 1 -1.77386834071664 0.789070791920946; 1 2 1 1 ...
        -1.76164675573411 0.776744465202476; 1 2 1 1 -1.75550592686558 ...
        0.770551008047455], ...
        'ScaleValues', [0.00420106933455496; 0.00411031041404182; ...
        0.00402729152858992; 0.00395369617686832; 0.00389080351858551; ...
        0.00383955386274487; 0.00380061280107605; 0.00377442736709098; ...
        0.00376127029546889; 1]);
end

y = step(Hd,x);


